//! FieldEdge Rust core crate
//!
//! Provides the in-process vector store, sync orchestrator, conflict
//! resolution, and Write-Ahead Log for the FieldEdge offline-first
//! mobile AI platform.

#![allow(warnings)]
#![allow(clippy::needless_return)]

pub mod edge;
pub mod sync;
pub mod conflict;
pub mod wal;
pub mod models;
pub mod crypto;
pub mod ffi;
pub mod embedding;
pub mod observability;

// UniFFI scaffolding is generated by build.rs (uniffi/field_edge.udl).
// The `uniffi` feature enables it; the public FFI surface is in `ffi::exports`.

use tracing_subscriber::EnvFilter;

/// Initialize logging. Idempotent; safe to call multiple times.
pub fn init_logging() {
    let _ = tracing_subscriber::fmt()
        .with_env_filter(
            EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info")),
        )
        .with_target(false)
        .try_init();
}
