//! Point payload schema — matches FR-031 in PRD.
//!
//! # Schema versioning
//!
//! [`Payload`] is the unified wire/storage type (currently v2). Older v1
//! payloads can still be read via [`VersionedPayload::from_bytes`] and
//! migrated with [`VersionedPayload::migrate_to_v2`].
//!
//! Bump [`CURRENT_SCHEMA_VERSION`] when adding/removing fields, and add a
//! new variant to [`VersionedPayload`] with the matching migrator.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Payload schema version. Bump when adding/removing fields.
pub const CURRENT_SCHEMA_VERSION: u32 = 2;

/// GPS status enum (matches PRD)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GpsStatus {
    Ok,
    Unavailable,
    Denied,
}

/// Embedding status enum
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EmbeddingStatus {
    Ok,
    Pending,
    Failed,
}

/// An enrichment object-detection result
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EnrichmentObject {
    pub label: String,
    /// Box as [x_min, y_min, x_max, y_max] in pixels
    pub box_: Vec<f32>,
    pub confidence: f32,
}

/// v1 payload schema — original field set, no soft-delete, no project owner,
/// no second-tag list.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PayloadV1 {
    pub schema_version: u32,
    pub photo_id: String,
    pub device_id: String,
    pub captured_at: String, // ISO-8601 UTC
    pub lat: Option<f64>,
    pub lng: Option<f64>,
    pub gps_status: GpsStatus,
    pub project_id: String,
    pub file_path: String,
    pub embedding_status: EmbeddingStatus,
    pub enrichment_id: Option<String>,
    pub enrichment_tags: Vec<String>,
    pub enrichment_objects: Vec<EnrichmentObject>,
    pub enrichment_text: Option<String>,
    pub synced_at: Option<String>,
    pub local_updated_at: String,
    pub vector_checksum: String,
}

/// v2 payload schema — adds soft-delete, project owner, and a secondary
/// tag list that is independent from `enrichment_tags` (which is reserved
/// for server-side enrichment output).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PayloadV2 {
    pub schema_version: u32,
    pub photo_id: String,
    pub device_id: String,
    pub captured_at: String, // ISO-8601 UTC
    pub lat: Option<f64>,
    pub lng: Option<f64>,
    pub gps_status: GpsStatus,
    pub project_id: String,
    pub file_path: String,
    pub embedding_status: EmbeddingStatus,
    pub enrichment_id: Option<String>,
    pub enrichment_tags: Vec<String>,
    pub enrichment_objects: Vec<EnrichmentObject>,
    pub enrichment_text: Option<String>,
    pub synced_at: Option<String>,
    pub local_updated_at: String,
    pub vector_checksum: String,
    /// Soft-delete flag. v2+ points stay in the store but are filtered out of queries.
    #[serde(default)]
    pub deletion_marker: bool,
    /// Owning user/team identifier (optional — backfilled from project_id when missing).
    #[serde(default)]
    pub project_owner: Option<String>,
    /// Independent tag list (free-form, not generated by the enrichment pipeline).
    #[serde(default)]
    pub tags_v2: Vec<String>,
}

/// Backwards-compatible alias: the canonical payload on the wire is v2.
/// External modules that import `Payload` keep working unchanged.
pub type Payload = PayloadV2;

/// Versioned envelope — the read-side dispatcher that detects the schema
/// version from a JSON value and lets the caller upgrade to the current
/// version in one step.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum VersionedPayload {
    V1(PayloadV1),
    V2(PayloadV2),
}

impl VersionedPayload {
    /// Detect schema version from raw JSON bytes and parse as the matching
    /// variant. Falls back to v1 when the field is missing or unrecognized —
    /// the original wire format predates the discriminator.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        let value: serde_json::Value = serde_json::from_slice(bytes)?;
        Self::from_value(value)
    }

    /// Detect schema version from a JSON value (or mutable variant) and
    /// parse as the matching variant. Falls back to v1 when the field is
    /// missing or unrecognized.
    pub fn from_value(mut value: serde_json::Value) -> Result<Self, serde_json::Error> {
        let version = value
            .get("schema_version")
            .and_then(|v| v.as_u64())
            .unwrap_or(1);

        // For v1 we synthesize a default tag if the field is absent so the
        // struct (which requires `schema_version`) still validates.
        if version == 1 {
            if let serde_json::Value::Object(ref mut map) = value {
                map.entry("schema_version".to_string())
                    .or_insert(serde_json::Value::from(1u32));
            }
        }

        match version {
            1 => serde_json::from_value::<PayloadV1>(value).map(VersionedPayload::V1),
            2 => serde_json::from_value::<PayloadV2>(value).map(VersionedPayload::V2),
            other => Err(serde_json::Error::io(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("unknown payload schema_version: {}", other),
            ))),
        }
    }

    /// Upgrade any variant to the current wire format (v2).
    ///
    /// Rules:
    /// - v2 → v2: identity.
    /// - v1 → v2: set `deletion_marker=false`, `project_owner=None`,
    ///   copy `enrichment_tags` into `tags_v2`.
    pub fn migrate_to_v2(self) -> PayloadV2 {
        match self {
            VersionedPayload::V2(v2) => v2,
            VersionedPayload::V1(v1) => PayloadV2 {
                schema_version: CURRENT_SCHEMA_VERSION,
                photo_id: v1.photo_id,
                device_id: v1.device_id,
                captured_at: v1.captured_at,
                lat: v1.lat,
                lng: v1.lng,
                gps_status: v1.gps_status,
                project_id: v1.project_id,
                file_path: v1.file_path,
                embedding_status: v1.embedding_status,
                enrichment_id: v1.enrichment_id,
                enrichment_tags: v1.enrichment_tags.clone(),
                enrichment_objects: v1.enrichment_objects,
                enrichment_text: v1.enrichment_text,
                synced_at: v1.synced_at,
                local_updated_at: v1.local_updated_at,
                vector_checksum: v1.vector_checksum,
                deletion_marker: false,
                project_owner: None,
                tags_v2: v1.enrichment_tags,
            },
        }
    }
}

impl PayloadV2 {
    pub fn current_version(&self) -> u32 {
        self.schema_version
    }

    /// Merge another payload into this one, with field-level rules:
    /// - server-owned fields always take from `other`
    /// - first-write-wins fields: error if they differ
    /// - last-write-wins fields: take from `other` if its local_updated_at is newer
    pub fn merge(&self, other: &PayloadV2) -> PayloadV2 {
        let mut merged = self.clone();

        // Server-owned fields always overwrite
        merged.enrichment_id = other.enrichment_id.clone();
        merged.enrichment_tags = other.enrichment_tags.clone();
        merged.enrichment_objects = other.enrichment_objects.clone();
        merged.enrichment_text = other.enrichment_text.clone();
        merged.synced_at = other.synced_at.clone();

        // v2: server-owned soft-delete and owner fields also overwrite.
        merged.deletion_marker = other.deletion_marker;
        merged.project_owner = other.project_owner.clone();
        merged.tags_v2 = other.tags_v2.clone();

        // Last-write-wins on local_updated_at
        merged.local_updated_at = if other.local_updated_at > self.local_updated_at {
            other.local_updated_at.clone()
        } else {
            self.local_updated_at.clone()
        };

        // Take whichever has newer local_updated_at for project_id
        if other.local_updated_at > self.local_updated_at {
            merged.project_id = other.project_id.clone();
        }

        merged
    }
}

// Backwards-compatible free functions for callers that haven't switched to
// the V2-aware types.
pub fn payload_to_json(payload: &Payload) -> Result<JsonValue, serde_json::Error> {
    serde_json::to_value(payload)
}

pub fn payload_from_json(value: &JsonValue) -> Result<Payload, serde_json::Error> {
    serde_json::from_value(value.clone())
}

/// Generic JSON value type for free-form fields in API requests
pub type JsonValue = serde_json::Value;

/// Generic field container for storing free-form metadata alongside a vector
pub type FieldMap = BTreeMap<String, JsonValue>;

#[cfg(test)]
mod tests {
    use super::*;

    fn make_v1_json(photo_id: &str) -> String {
        format!(
            r#"{{
                "schema_version": 1,
                "photo_id": "{photo_id}",
                "device_id": "dev1",
                "captured_at": "2025-05-12T14:23:01Z",
                "lat": 12.34,
                "lng": 56.78,
                "gps_status": "ok",
                "project_id": "p1",
                "file_path": "/photos/x.jpg",
                "embedding_status": "ok",
                "enrichment_id": "abc",
                "enrichment_tags": ["alpha", "beta"],
                "enrichment_objects": [],
                "enrichment_text": null,
                "synced_at": null,
                "local_updated_at": "2025-05-12T14:23:01Z",
                "vector_checksum": "sha256:xyz"
            }}"#
        )
    }

    fn make_v2_json(photo_id: &str) -> String {
        format!(
            r#"{{
                "schema_version": 2,
                "photo_id": "{photo_id}",
                "device_id": "dev1",
                "captured_at": "2025-05-12T14:23:01Z",
                "lat": 12.34,
                "lng": 56.78,
                "gps_status": "ok",
                "project_id": "p1",
                "file_path": "/photos/x.jpg",
                "embedding_status": "ok",
                "enrichment_id": "abc",
                "enrichment_tags": ["alpha", "beta"],
                "enrichment_objects": [],
                "enrichment_text": null,
                "synced_at": null,
                "local_updated_at": "2025-05-12T14:23:01Z",
                "vector_checksum": "sha256:xyz",
                "deletion_marker": false,
                "project_owner": "alice",
                "tags_v2": ["x", "y"]
            }}"#
        )
    }

    #[test]
    fn from_bytes_reads_v1() {
        let raw = make_v1_json("p1");
        let v = VersionedPayload::from_bytes(raw.as_bytes()).expect("parse v1");
        match &v {
            VersionedPayload::V1(p) => {
                assert_eq!(p.photo_id, "p1");
                assert_eq!(p.enrichment_tags, vec!["alpha", "beta"]);
            }
            _ => panic!("expected V1"),
        }
    }

    #[test]
    fn from_bytes_reads_v2() {
        let raw = make_v2_json("p2");
        let v = VersionedPayload::from_bytes(raw.as_bytes()).expect("parse v2");
        match &v {
            VersionedPayload::V2(p) => {
                assert_eq!(p.photo_id, "p2");
                assert_eq!(p.project_owner.as_deref(), Some("alice"));
                assert_eq!(p.tags_v2, vec!["x", "y"]);
                assert!(!p.deletion_marker);
            }
            _ => panic!("expected V2"),
        }
    }

    #[test]
    fn from_bytes_missing_version_defaults_to_v1() {
        // schema_version absent → treat as v1 (the original wire format).
        let raw = r#"{
            "photo_id": "p3",
            "device_id": "dev1",
            "captured_at": "2025-05-12T14:23:01Z",
            "lat": null, "lng": null,
            "gps_status": "ok",
            "project_id": "p1",
            "file_path": "/photos/x.jpg",
            "embedding_status": "ok",
            "enrichment_id": null,
            "enrichment_tags": [],
            "enrichment_objects": [],
            "enrichment_text": null,
            "synced_at": null,
            "local_updated_at": "2025-05-12T14:23:01Z",
            "vector_checksum": "sha256:xyz"
        }"#;
        let v = VersionedPayload::from_bytes(raw.as_bytes()).expect("parse");
        assert!(matches!(v, VersionedPayload::V1(_)));
    }

    #[test]
    fn migrate_v1_to_v2() {
        let raw = make_v1_json("p4");
        let v = VersionedPayload::from_bytes(raw.as_bytes()).unwrap();
        let migrated = v.migrate_to_v2();
        assert_eq!(migrated.schema_version, CURRENT_SCHEMA_VERSION);
        assert!(!migrated.deletion_marker);
        assert!(migrated.project_owner.is_none());
        assert_eq!(migrated.tags_v2, vec!["alpha", "beta"]);
        assert_eq!(migrated.photo_id, "p4");
    }

    #[test]
    fn migrate_v2_to_v2_is_identity() {
        let raw = make_v2_json("p5");
        let v = VersionedPayload::from_bytes(raw.as_bytes()).unwrap();
        let migrated = v.migrate_to_v2();
        assert_eq!(migrated.project_owner.as_deref(), Some("alice"));
        assert_eq!(migrated.tags_v2, vec!["x", "y"]);
    }

    #[test]
    fn round_trip_v2_through_bytes() {
        let raw = make_v2_json("p6");
        let v = VersionedPayload::from_bytes(raw.as_bytes()).unwrap();
        let migrated = v.migrate_to_v2();
        let reencoded = serde_json::to_string(&migrated).unwrap();
        let reparsed = VersionedPayload::from_bytes(reencoded.as_bytes()).unwrap();
        match reparsed {
            VersionedPayload::V2(p) => {
                assert_eq!(p.photo_id, "p6");
                assert_eq!(p.tags_v2, vec!["x", "y"]);
            }
            _ => panic!("re-encoded as V1"),
        }
    }

    #[test]
    fn merge_v2_overwrites_v2_owner_fields() {
        let local = PayloadV2 {
            schema_version: 2,
            photo_id: "p".into(),
            device_id: "d".into(),
            captured_at: "2025-05-12T14:23:01Z".into(),
            lat: None,
            lng: None,
            gps_status: GpsStatus::Ok,
            project_id: "A".into(),
            file_path: "f".into(),
            embedding_status: EmbeddingStatus::Ok,
            enrichment_id: None,
            enrichment_tags: vec![],
            enrichment_objects: vec![],
            enrichment_text: None,
            synced_at: None,
            local_updated_at: "2025-05-12T14:23:01Z".into(),
            vector_checksum: "sha256:abc".into(),
            deletion_marker: false,
            project_owner: None,
            tags_v2: vec![],
        };
        let mut remote = local.clone();
        remote.local_updated_at = "2025-05-12T14:23:02Z".into();
        remote.project_owner = Some("alice".into());
        remote.tags_v2 = vec!["x".into()];
        remote.deletion_marker = true;

        let merged = local.merge(&remote);
        assert!(merged.deletion_marker);
        assert_eq!(merged.project_owner.as_deref(), Some("alice"));
        assert_eq!(merged.tags_v2, vec!["x".to_string()]);
    }
}
